### ISSUE TITLE
Add support for consumer priority (x-priority header)

### ISSUE THREAD

**Issue by yuhusolutions** [rabbitmq/rabbitmq-stomp#122]
Hi,
According to https://www.rabbitmq.com/consumer-priority.html 
it should be possible to pass the "x-priority" header in the subscribe method, however this seems to have no effect on the consumer definition when using the Stomp adapter (over Websocket) https://www.rabbitmq.com/web-stomp.html.

While attempting with the Java lib, we can see that it works (see attachment).
![image](https://user-images.githubusercontent.com/29959338/33468041-492f8890-d627-11e7-9a07-68fa393e6ad5.png)

Other args for the queue like "x-message-ttl" work fine.

Rabbit mq version: 
3.6.14 Erlang 19.2.3
More detail can be found in the following thread:
[discussion in the mailing list](https://groups.google.com/forum/#!topic/rabbitmq-users/OlUWdn6K53Y)

Regards,

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@mindscratch is correct, the header name is `x-max-priority`.
